
workdir: /data02/project/TBD200742_WGRS_Human_siyoo_202011/de_novo_mutation_calling_pipeline
reference:
  genome_fasta: reference/Homo_sapiens_assembly38.fasta
  known_site_1: reference/Homo_sapiens_assembly38.dbsnp138.vcf
  known_site_2: reference/Mills_and_1000G_gold_standard.indels.hg38.vcf
snpeff_config: /TBI/People/tbi/siyoo/miniconda3/envs/de_novo_mutation_calling_pipeline/share/snpeff-5.0-0/snpEff.config
snpeff_db: hg38
dbsnp_db: /TBI/Share/BioPeople/shsong/BioResources/DBs/dbsnp/v150/GRCh38/00-All.vcf.gz
clinvar_db: /TBI/Share/BioPeople/shsong/BioResources/DBs/clinvar/20200905/GRCh38/clinvar.vcf.gz

samples:
  sample_K-ABC-00209:
    fastq_1: rawdata/TBD210101_11481_20210303/sample_K-ABC-00209_1.fq.gz
    fastq_2: rawdata/TBD210101_11481_20210303/sample_K-ABC-00209_2.fq.gz
  sample_K-ABC-00278:
    fastq_1: rawdata/TBD210101_11481_20210303/sample_K-ABC-00278_1.fq.gz
    fastq_2: rawdata/TBD210101_11481_20210303/sample_K-ABC-00278_2.fq.gz
